theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true

deployment:
  targets:
    - name: "production"
      URL: "s3://www.technorealisme.org?endpoint=garage.deuxfleurs.fr&s3ForcePathStyle=true&region=garage"

params:
  breadcrumb:
    position: hero-start
  summary:
    position: hero
  logo:
    header: "/assets/images/logo.svg"
    footer: "/assets/images/icon-color.svg"
  pages:
    index:
      truncate_description: 0
  posts:
    index:
      show_author: true
      show_description: true
      truncate_description: 0
      layout: grid
